#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);


templates2events("/etc/ejabberd/ejabberd.cfg",  qw(
	bootstrap-console-save
	ejabberd-update
	));

templates2events("/etc/pam.d/ejabberd", qw(ejabberd-update bootstrap-console-save));
templates2events("/etc/logrotate.d/ejabberd", qw(ejabberd-update bootstrap-console-save));
templates2events("/etc/httpd/conf/httpd.conf", "ejabberd-update");
templates2events("/etc/jappix/main.xml", "ejabberd-update");
templates2events("/etc/rc.d/init.d/masq", "ejabberd-update");
templates2events("/etc/e-smith/sql/init/80ejabberd", "bootstrap-console-save");

#--------------------------------------------------
# ejabberd-update actions
#--------------------------------------------------

event_link("ejabberd-init-domain", 'ejabberd-update', "10");
event_link("ejabberd-init-domain", 'ipasserelle-update', "60");
event_link("ejabberd-init-domain", 'webapps-update', "60");

safe_symlink("restart", "root/etc/e-smith/events/ejabberd-update/services2adjust/ejabberd");
safe_symlink("adjust", "root/etc/e-smith/events/ejabberd-update/services2adjust/masq");
safe_symlink("sigusr1", "root/etc/e-smith/events/ejabberd-update/services2adjust/httpd-e-smith");

#--------------------------------------------------
# startup and stop symlink
#--------------------------------------------------
service_link_enhanced("ejabberd", "S90", "7");
service_link_enhanced("ejabberd", "K25", "6");
service_link_enhanced("ejabberd", "K25", "1");
service_link_enhanced("ejabberd", "K25", "0");

# Daemontools links.
safe_symlink("../daemontools", "root/etc/rc.d/init.d/supervise/ejabberd");
safe_symlink("../var/service/ejabberd", "root/service/ejabberd");

# Symlink for the cgi.
panel_link("ejabberd", "manager");

exit;
